version: '3.4'
volumes:
  publics: {}

services:
  testdocker:
    image: testdocker
    build:
      context: .
      dockerfile: ./Dockerfile-Root
    volumes:
      - publics:/app/wwwroot/public:rw
    ports:
      - 80:5000